<a href="https://colab.research.google.com/github/minjibyeongho/KOSA-Pytorch/blob/main/1_linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x = torch.randn(2,3)

In [ ]:
y = torch.rand(2,3)

In [ ]:
a = x.to('cuda')

In [ ]:
#python

In [ ]:
# Y = Wx + b
# input: 10 Ouput: 5 Linear Transform

In [1]:
import torch
from torch.autograd import Variable
from torch.nn import Linear

data = Variable(torch.randn(1, 10))
Layer =Linear(in_features=10, out_features=5, bias=True)

In [2]:
data

tensor([[-1.0727e-01,  1.3842e-03, -6.8433e-01, -1.9900e+00,  6.4010e-01,
         -1.4556e+00,  2.9070e-01, -4.2521e-01,  4.6067e-01, -2.1953e-01]])

In [3]:
Layer(data)

tensor([[ 0.2283, -0.4164,  0.2959, -0.0462, -0.8715]],
       grad_fn=<AddmmBackward>)

In [4]:
Layer.weight

Parameter containing:
tensor([[-0.2323,  0.1153, -0.2637, -0.1299, -0.2839,  0.0840,  0.2670,  0.1083,
         -0.2213,  0.1851],
        [ 0.1939, -0.1476, -0.1677,  0.3081,  0.2739, -0.0144, -0.1872, -0.2238,
         -0.0259, -0.2537],
        [-0.2391, -0.2466, -0.3141,  0.1033, -0.2071, -0.1282, -0.0125, -0.0132,
         -0.2040,  0.0666],
        [ 0.0338,  0.2634,  0.2998,  0.2650,  0.1322, -0.1855,  0.2477,  0.1618,
          0.3002,  0.1203],
        [ 0.0346,  0.2706,  0.3125,  0.2399, -0.1779,  0.0744, -0.1356, -0.2671,
          0.0119, -0.3092]], requires_grad=True)

In [5]:
Layer.bias

Parameter containing:
tensor([ 0.1794, -0.1779,  0.3137,  0.2199, -0.1022], requires_grad=True)

In [ ]:
# Activation Function -> ReLu

In [6]:
from torch.nn import ReLU
import torch

In [7]:
data = torch.Tensor([[3, 1, 2, -1, -3]])

In [8]:
relu = ReLU()
relu(data)

tensor([[3., 1., 2., 0., 0.]])

In [ ]:
# Feedforward & Back Propagation
# https://blog.naver.com/slykid/222007253786

In [9]:
import torch
from torch import nn
from torch.autograd import Variable

In [11]:
class Network_ex(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(Network_ex).__init__()
        self.layer1 = nn.Linear(input_size, hidden_size)
        self.layer2 = nn.Linear(hidden_size, output_size)
        
    def forward(self, input):
        out = self.Layer1(input)
        out = nn.ReLU(out)
        out = self.layer2(out)
        
        return out

In [12]:
loss = nn.MSELoss()
data = Variable(torch.randn(3, 5), requires_grad=True)

In [13]:
data

tensor([[ 0.1355, -1.5169,  1.3240, -0.4665,  0.7517],
        [ 0.2055,  0.3371,  0.8541, -2.8851, -0.4420],
        [-0.3627,  1.4916, -0.3071,  0.3949, -0.9249]], requires_grad=True)

In [15]:
target = Variable(torch.randn(3, 5))

In [16]:
target

tensor([[-0.0628,  1.2125, -0.9346, -0.1303, -0.3487],
        [-0.9802,  0.8536,  1.4952,  0.5643, -1.4151],
        [ 0.1242, -0.9944,  0.2274, -0.1031, -2.1872]])

In [17]:
output = loss(data, target)
output.backward()

In [18]:
output

tensor(2.4925, grad_fn=<MseLossBackward>)